ln -s /homes/ttmt001/kaldi/src/base/libkaldi-base.so /homes/ttmt001/kaldi/src/lib/libkaldi-base.so 
ln -s /homes/ttmt001/kaldi/src/chain/libkaldi-chain.so /homes/ttmt001/kaldi/src/lib/libkaldi-chain.so 
ln -s /homes/ttmt001/kaldi/src/cudamatrix/libkaldi-cudamatrix.so /homes/ttmt001/kaldi/src/lib/libkaldi-cudamatrix.so
ln -s /homes/ttmt001/kaldi/src/decoder/libkaldi-decoder.so /homes/ttmt001/kaldi/src/lib/libkaldi-decoder.so 
ln -s /homes/ttmt001/kaldi/src/feat/libkaldi-feat.so /homes/ttmt001/kaldi/src/lib/libkaldi-feat.so 
ln -s /homes/ttmt001/kaldi/src/fstext/libkaldi-fstext.so /homes/ttmt001/kaldi/src/lib/libkaldi-fstext.so 
ln -s /homes/ttmt001/kaldi/src/gmm/libkaldi-gmm.so /homes/ttmt001/kaldi/src/lib/libkaldi-gmm.so 
ln -s /homes/ttmt001/kaldi/src/hmm/libkaldi-hmm.so /homes/ttmt001/kaldi/src/lib/libkaldi-hmm.so 
ln -s /homes/ttmt001/kaldi/src/ivector/libkaldi-ivector.so /homes/ttmt001/kaldi/src/lib/libkaldi-ivector.so 
ln -s /homes/ttmt001/kaldi/src/kws/libkaldi-kws.so /homes/ttmt001/kaldi/src/lib/libkaldi-kws.so 
ln -s /homes/ttmt001/kaldi/src/lat/libkaldi-lat.so /homes/ttmt001/kaldi/src/lib/libkaldi-lat.so 
ln -s /homes/ttmt001/kaldi/src/lm/libkaldi-lm.so /homes/ttmt001/kaldi/src/lib/libkaldi-lm.so 
ln -s /homes/ttmt001/kaldi/src/matrix/libkaldi-matrix.so /homes/ttmt001/kaldi/src/lib/libkaldi-matrix.so 
ln -s /homes/ttmt001/kaldi/src/nnet2/libkaldi-nnet2.so /homes/ttmt001/kaldi/src/lib/libkaldi-nnet2.so 
ln -s /homes/ttmt001/kaldi/src/nnet3/libkaldi-nnet3.so /homes/ttmt001/kaldi/src/lib/libkaldi-nnet3.so 
ln -s /homes/ttmt001/kaldi/src/nnet/libkaldi-nnet.so /homes/ttmt001/kaldi/src/lib/libkaldi-nnet.so 
ln -s /homes/ttmt001/kaldi/src/online2/libkaldi-online2.so /homes/ttmt001/kaldi/src/lib/libkaldi-online2.so 
ln -s /homes/ttmt001/kaldi/src/sgmm2/libkaldi-sgmm2.so /homes/ttmt001/kaldi/src/lib/libkaldi-sgmm2.so 
ln -s /homes/ttmt001/kaldi/src/thread/libkaldi-thread.so /homes/ttmt001/kaldi/src/lib/libkaldi-thread.so 
ln -s /homes/ttmt001/kaldi/src/transform/libkaldi-transform.so /homes/ttmt001/kaldi/src/lib/libkaldi-transform.so 
ln -s /homes/ttmt001/kaldi/src/tree/libkaldi-tree.so /homes/ttmt001/kaldi/src/lib/libkaldi-tree.so 
ln -s /homes/ttmt001/kaldi/src/util/libkaldi-util.so /homes/ttmt001/kaldi/src/lib/libkaldi-util.so 
